version: "3.8"
services:
  web:
    image: gsguglielmo/nodejs
    command: npm run server:start:debug
    tty: true
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_DATABASE=${DATABASE_NAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - ENVIRONMENT=dev
    volumes:
      - /data/projects/${PROJECT}:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}.rule=Host(`${PROJECT}.${DOMAIN}.codingduck.it`)
      # Add public and public-secure to allow access from outside the VPN
      - traefik.http.routers.${PROJECT}.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.${PROJECT}.tls=true
      # Uncomment this for let's encrypt certificate
      - traefik.http.routers.${PROJECT}.tls.certresolver=${CERTIFICATE}
  db:
    image: mariadb
    restart: always
    volumes:
      - database-volume:/var/lib/mysql
      - /databaseDump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}db.rule=Host(`db-${PROJECT}.dev.codingduck.it`)
      - traefik.http.routers.${PROJECT}db.entrypoints=private,private-secure
      - traefik.http.routers.${PROJECT}db.tls=true

volumes:
  database-volume:
