version: "3.8"
services:
  web:
    image: gsguglielmo/phpdevelopment:8.1.3
    # Change the UID and GID to reflect the mounted folder permissions
    command: ["apache2-foreground", "--user $$USER_UID:$$USER_GID"]
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_DATABASE=test-db
      - DB_PASSWORD=testroot1
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}${USERNAME}.rule=Host(`${PROJECT}-${USERNAME}.dev.codingduck.it`)
      # Add public and public-secure to allow access from outside the VPN
      - traefik.http.routers.${PROJECT}${USERNAME}.entrypoints=private,private-secure
      - traefik.http.routers.${PROJECT}${USERNAME}.tls=true
      # Uncomment this for let's encrypt certificate
      #- traefik.http.routers.${PROJECT}.tls.certresolver=${CERTIFICATE}
    volumes:
      - /home/${USERNAME}/${PROJECTPATH}:/var/www/html/
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - database-volume:/var/lib/mysql
      - /databaseDump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: testroot1
      MYSQL_DATABASE: test-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: testroot1
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}db${USERNAME}.rule=Host(`db-${PROJECT}-${USERNAME}.dev.codingduck.it`)
      - traefik.http.routers.${PROJECT}db${USERNAME}.entrypoints=private,private-secure
      - traefik.http.routers.${PROJECT}db${USERNAME}.tls=true

volumes:
  database-volume:
